using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CowUtters
{

    //Attribution Note: documentation of this class has been autogenerated by my good friend github copilot
    public class Utterance
    {
        /// <summary>
        /// Gets or sets the speaker of the utterance.
        /// </summary>
        public string? speaker { get; set; }

        /// <summary>
        /// Gets or sets the text of the utterance.
        /// </summary>
        public string? text { get; set; }

        /// <summary>
        /// Gets or sets the timestamp in milliseconds of the utterance.
        /// </summary>
        public ulong timestampMs { get; set; }

        /// <summary>
        /// Compares the speaker value of the current Utterance object with the input Utterance object.
        /// </summary>
        /// <param name="inval">The Utterance object to compare with.</param>
        /// <returns>True if both objects have valid speakers (non-null) and are the same speaker, otherwise false.</returns>
        public bool sameSpeaker(Utterance? inval)
        {
            if (inval != null && !string.IsNullOrEmpty(this.speaker))
            {
                return this.speaker == inval.speaker;
            }
            return false;
        }

        /// <summary>
        /// Checks if the text of the utterance was a complete sentence (ended in.
        /// </summary>
        /// <returns>True if the text ends with '.', '!', or '?', otherwise false.</returns>
        /// <exception cref="InvalidDataException">Thrown when the text is null or empty.</exception>
        public bool endsInPunctuation()
        {
            if (string.IsNullOrEmpty(text))
            {
                return false;
            }
            return indexOfLastPunctuation() == (text.Length - 1);
        }

        public int indexOfLastPunctuation()
        {
            if (string.IsNullOrEmpty(text))
            {
                return -1;
            }
            return this.text.LastIndexOfAny(".!?".ToCharArray());
        }

        public int indexOfFirstPunctuation()
        {
            if (string.IsNullOrEmpty(text))
            {
                return -1;
            }
            return this.text.IndexOfAny(".!?".ToCharArray());

        }

    }

    public class Utterances
    {

        public List<Utterance> utterances { get; set; }
        public Utterances()
        {
            utterances = new List<Utterance>();
        }
    }

}

